import React, { createContext, useContext, useState, useCallback, ReactNode } from 'react';

export type Language = 'en' | 'es' | 'fr' | 'de' | 'tr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const STORAGE_KEY = 'heartsync_language';

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    try {
      const stored = localStorage.getItem(STORAGE_KEY);
      if (stored && ['en', 'es', 'fr', 'de', 'tr'].includes(stored)) {
        return stored as Language;
      }
    } catch {
      // localStorage not available
    }
    return 'en';
  });

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
    try {
      localStorage.setItem(STORAGE_KEY, lang);
    } catch {
      // localStorage not available
    }
  }, []);

  const t = useCallback((key: string): string => {
    const keys = key.split('.');
    let value: unknown = translations[language];

    for (const k of keys) {
      if (value && typeof value === 'object' && k in value) {
        value = (value as Record<string, unknown>)[k];
      } else {
        // Fallback to English
        value = translations['en'];
        for (const fallbackKey of keys) {
          if (value && typeof value === 'object' && fallbackKey in value) {
            value = (value as Record<string, unknown>)[fallbackKey];
          } else {
            return key;
          }
        }
        break;
      }
    }

    return typeof value === 'string' ? value : key;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export function useLanguage(): LanguageContextType {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

// Translation dictionary
const translations: Record<Language, Record<string, unknown>> = {
  en: {
    nav: {
      discover: 'Discover',
      messages: 'Messages',
      upgrade: 'Upgrade',
      settings: 'Settings',
      profile: 'Profile',
      signIn: 'Sign In',
      getStarted: 'Get Started',
      logOut: 'Log Out',
    },
    buttons: {
      save: 'Save',
      cancel: 'Cancel',
      edit: 'Edit',
      delete: 'Delete',
      confirm: 'Confirm',
      back: 'Back',
      continue: 'Continue',
      close: 'Close',
      send: 'Send',
      search: 'Search',
      startMatching: 'Start Matching',
      viewMatches: 'View Matches',
    },
    auth: {
      createAccount: 'Create Account',
      welcomeBack: 'Welcome Back',
      startJourney: 'Start your journey to find love',
      signInToContinue: 'Sign in to continue',
      signUp: 'Sign Up',
      signIn: 'Sign In',
      fullName: 'Full Name',
      email: 'Email',
      password: 'Password',
      minCharacters: 'Min 6 characters',
      byContinuing: 'By continuing, you agree to our Terms and Privacy Policy.',
    },
    settings: {
      title: 'Settings',
      websiteLanguage: 'Website Language',
      languageDescription: 'Changes the language of the HeartSync interface only.',
      signOut: 'Sign out',
      signOutDescription: 'Sign out of your HeartSync account',
      deleteAccount: 'Delete account',
      deleteAccountDescription: 'Permanently delete your account and all data',
      deleteConfirmTitle: 'Delete your account?',
      deleteConfirmMessage: 'This action is permanent and cannot be undone. All your data, matches, and messages will be permanently deleted.',
      deleteConfirmNote: 'Account deletion requires backend implementation',
    },
    profile: {
      title: 'My Profile',
      bio: 'Bio',
      bioPlaceholder: 'Tell others about yourself...',
      noBio: 'No bio yet. Click edit to add one!',
      photos: 'Photos',
      interests: 'Interests',
      addInterest: 'Add interest...',
      add: 'Add',
      main: 'MAIN',
      addPhoto: 'Add Photo',
      camera: 'Camera',
      upload: 'Upload',
      likes: 'Likes',
      matches: 'Matches',
      views: 'Views',
      interestedIn: 'Interested in',
      gender: 'Gender',
      age: 'Age',
      location: 'Location',
      name: 'Name',
      premiumActive: 'Premium Active',
      planDaysRemaining: 'plan · days remaining',
    },
    upgrade: {
      title: 'Upgrade to Premium',
      subtitle: "Unlock unlimited messaging, see who's online, and connect with exclusive profiles",
      yourePremium: "You're Premium!",
      whatYouGet: 'What You Get',
      yourPremiumPerks: 'Your Premium Perks',
      unlimitedMessages: 'Unlimited Messages',
      unlimitedMessagesDesc: 'Chat without limits with all your matches',
      seeWhosOnline: "See Who's Online",
      seeWhosOnlineDesc: 'Know when your matches are available',
      unlimitedLikes: 'Unlimited Likes',
      unlimitedLikesDesc: 'Like as many profiles as you want',
      superLikes: 'Super Likes',
      superLikesDesc: 'Stand out with unlimited super likes',
      prioritySupport: 'Priority Support',
      prioritySupportDesc: 'Get help faster when you need it',
      vipBadge: 'VIP Badge',
      vipBadgeDesc: 'Show off your premium status',
      choosePlan: 'Choose',
      readyToFind: 'Ready to Find Your Match?',
      joinPremium: 'Join premium today and unlock all features to find your perfect connection',
      upgradeNow: 'Upgrade Now',
    },
    messages: {
      title: 'Messages',
      searchConversations: 'Search conversations...',
      noConversations: 'No conversations yet. Start swiping to match!',
      tapToStart: 'Tap to start chatting...',
      sayHi: 'Say hi to',
      sendAMessage: 'Send a message to start chatting',
      typeMessage: 'Type a message...',
      subscribeToSend: 'Subscribe to send messages...',
      onlineNow: 'Online now',
      lastSeen: 'Last seen recently',
      freeMessagesRemaining: 'free message(s) remaining with',
      freeMessagesExhausted: 'Free messages exhausted!',
      subscribeToContinue: 'Subscribe to keep chatting with',
      subscribeNow: 'Subscribe Now',
      slowDown: 'Slow down! Max 10 messages per minute.',
      yourMessages: 'Your Messages',
      selectConversation: 'Select a conversation to start chatting',
    },
    discover: {
      title: 'Discover',
      profilesRemaining: 'profiles remaining',
      youveSeenEveryone: "You've seen everyone!",
      checkBackLater: 'Check back later for new profiles.',
      startOver: 'Start Over',
      swipeUpToPass: 'Swipe up to pass • Left/Right to like',
      swipeOrTap: 'Swipe or tap buttons to interact',
      keyboard: 'Keyboard: ← Pass | → Like | ↑ Super Like',
      verified: 'Verified',
      live: 'Live',
    },
    matches: {
      title: 'Your Matches',
      subtitle: 'People who liked you back',
      new: 'NEW',
    },
    landing: {
      aiPowered: '#1 AI-Powered Dating Platform',
      findYourPerfectMatch: 'Find Your',
      perfect: 'Perfect',
      match: 'Match',
      landingSubtitle: 'Join millions of singles finding meaningful connections through our intelligent matching system. Your soulmate is just a swipe away.',
      freeToJoin: 'Free to join',
      verifiedProfiles: 'Verified profiles',
      secureDating: 'Secure dating',
      whyChoose: 'Why Choose',
      heartsync: 'HeartSync',
      whyChooseSubtitle: 'Every feature is designed to help you find genuine connections.',
      smartMatching: 'Smart Matching',
      smartMatchingDesc: 'AI-powered algorithm finds your ideal match',
      safeSecure: 'Safe & Secure',
      safeSecureDesc: 'Verified profiles and encrypted messaging',
      realConnections: 'Real Connections',
      realConnectionsDesc: 'Millions of genuine singles worldwide',
      premiumExperience: 'Premium Experience',
      premiumExperienceDesc: 'Seamless, polished dating experience',
      realStories: 'Real Stories,',
      realLove: 'Real Love',
      realStoriesSubtitle: 'Thousands of couples found their happily ever after on HeartSync.',
      readyToFindSoulmate: 'Ready to Find Your Soulmate?',
      joinToday: 'Join HeartSync today and start your journey to finding true love.',
      getStartedFree: 'Get Started Free',
      howItWorks: 'How It Works',
      createProfile: 'Create Profile',
      createProfileDesc: 'Sign up and build your profile with photos and interests.',
      discoverMatches: 'Discover Matches',
      discoverMatchesDesc: 'Swipe through profiles and like people you connect with.',
      startDating: 'Start Dating',
      startDatingDesc: 'Match and start meaningful conversations.',
      step: 'Step',
      activeUsers: 'Active Users',
      matchesMade: 'Matches Made',
      countries: 'Countries',
      successRate: 'Success Rate',
    },
    common: {
      loading: 'Loading...',
      profileUpdated: 'Profile updated successfully!',
      failedToSave: 'Failed to save changes. Please try again.',
      anErrorOccurred: 'An unexpected error occurred. Please try again.',
    },
  },

  es: {
    nav: {
      discover: 'Descubrir',
      messages: 'Mensajes',
      upgrade: 'Premium',
      settings: 'Ajustes',
      profile: 'Perfil',
      signIn: 'Iniciar sesión',
      getStarted: 'Comenzar',
      logOut: 'Cerrar sesión',
    },
    buttons: {
      save: 'Guardar',
      cancel: 'Cancelar',
      edit: 'Editar',
      delete: 'Eliminar',
      confirm: 'Confirmar',
      back: 'Atrás',
      continue: 'Continuar',
      close: 'Cerrar',
      send: 'Enviar',
      search: 'Buscar',
      startMatching: 'Comenzar a buscar',
      viewMatches: 'Ver coincidencias',
    },
    auth: {
      createAccount: 'Crear cuenta',
      welcomeBack: 'Bienvenido de nuevo',
      startJourney: 'Comienza tu viaje para encontrar el amor',
      signInToContinue: 'Inicia sesión para continuar',
      signUp: 'Registrarse',
      signIn: 'Iniciar sesión',
      fullName: 'Nombre completo',
      email: 'Correo electrónico',
      password: 'Contraseña',
      minCharacters: 'Mínimo 6 caracteres',
      byContinuing: 'Al continuar, aceptas nuestros Términos y Política de Privacidad.',
    },
    settings: {
      title: 'Ajustes',
      websiteLanguage: 'Idioma del sitio web',
      languageDescription: 'Cambia el idioma de la interfaz de HeartSync solamente.',
      signOut: 'Cerrar sesión',
      signOutDescription: 'Cierra sesión en tu cuenta de HeartSync',
      deleteAccount: 'Eliminar cuenta',
      deleteAccountDescription: 'Elimina permanentemente tu cuenta y todos los datos',
      deleteConfirmTitle: '¿Eliminar tu cuenta?',
      deleteConfirmMessage: 'Esta acción es permanente y no se puede deshacer. Todos tus datos, coincidencias y mensajes serán eliminados permanentemente.',
      deleteConfirmNote: 'La eliminación de cuenta requiere implementación del backend',
    },
    profile: {
      title: 'Mi Perfil',
      bio: 'Biografía',
      bioPlaceholder: 'Cuéntale a otros sobre ti...',
      noBio: '¡Aún no hay biografía. Haz clic en editar para agregar una!',
      photos: 'Fotos',
      interests: 'Intereses',
      addInterest: 'Agregar interés...',
      add: 'Agregar',
      main: 'PRINCIPAL',
      addPhoto: 'Agregar Foto',
      camera: 'Cámara',
      upload: 'Subir',
      likes: 'Me gusta',
      matches: 'Coincidencias',
      views: 'Vistas',
      interestedIn: 'Interesado en',
      gender: 'Género',
      age: 'Edad',
      location: 'Ubicación',
      name: 'Nombre',
      premiumActive: 'Premium Activo',
      planDaysRemaining: 'plan · días restantes',
    },
    upgrade: {
      title: 'Actualizar a Premium',
      subtitle: 'Desbloquea mensajes ilimitados, ve quién está en línea y conecta con perfiles exclusivos',
      yourePremium: '¡Eres Premium!',
      whatYouGet: 'Lo que obtienes',
      yourPremiumPerks: 'Tus beneficios Premium',
      unlimitedMessages: 'Mensajes Ilimitados',
      unlimitedMessagesDesc: 'Chatea sin límites con todas tus coincidencias',
      seeWhosOnline: 'Ve quién está en línea',
      seeWhosOnlineDesc: 'Sabe cuándo tus coincidencias están disponibles',
      unlimitedLikes: 'Me gusta ilimitados',
      unlimitedLikesDesc: 'Da me gusta a tantos perfiles como quieras',
      superLikes: 'Super Me gusta',
      superLikesDesc: 'Destaca con super me gusta ilimitados',
      prioritySupport: 'Soporte Prioritario',
      prioritySupportDesc: 'Obtén ayuda más rápido cuando la necesites',
      vipBadge: 'Insignia VIP',
      vipBadgeDesc: 'Muestra tu estado premium',
      choosePlan: 'Elegir',
      readyToFind: '¿Listo para encontrar tu pareja?',
      joinPremium: 'Únete a premium hoy y desbloquea todas las funciones para encontrar tu conexión perfecta',
      upgradeNow: 'Actualizar Ahora',
    },
    messages: {
      title: 'Mensajes',
      searchConversations: 'Buscar conversaciones...',
      noConversations: '¡Aún no hay conversaciones. Comienza a deslizar para encontrar coincidencias!',
      tapToStart: 'Toca para comenzar a chatear...',
      sayHi: 'Saluda a',
      sendAMessage: 'Envía un mensaje para comenzar a chatear',
      typeMessage: 'Escribe un mensaje...',
      subscribeToSend: 'Suscríbete para enviar mensajes...',
      onlineNow: 'En línea ahora',
      lastSeen: 'Visto recientemente',
      freeMessagesRemaining: 'mensaje(s) gratuito(s) restante(s) con',
      freeMessagesExhausted: '¡Mensajes gratuitos agotados!',
      subscribeToContinue: 'Suscríbete para seguir chateando con',
      subscribeNow: 'Suscribirse Ahora',
      slowDown: '¡Despacio! Máximo 10 mensajes por minuto.',
      yourMessages: 'Tus Mensajes',
      selectConversation: 'Selecciona una conversación para comenzar a chatear',
    },
    discover: {
      title: 'Descubrir',
      profilesRemaining: 'perfiles restantes',
      youveSeenEveryone: '¡Has visto a todos!',
      checkBackLater: 'Vuelve más tarde para ver nuevos perfiles.',
      startOver: 'Comenzar de nuevo',
      swipeUpToPass: 'Desliza hacia arriba para pasar • Izquierda/Derecha para me gusta',
      swipeOrTap: 'Desliza o toca los botones para interactuar',
      keyboard: 'Teclado: ← Pasar | → Me gusta | ↑ Super Me gusta',
      verified: 'Verificado',
      live: 'En vivo',
    },
    matches: {
      title: 'Tus Coincidencias',
      subtitle: 'Personas que también te dieron me gusta',
      new: 'NUEVO',
    },
    landing: {
      aiPowered: '#1 Plataforma de Citas con IA',
      findYourPerfectMatch: 'Encuentra tu',
      perfect: 'pareja',
      match: 'perfecta',
      landingSubtitle: 'Únete a millones de solteros que encuentran conexiones significativas a través de nuestro sistema de emparejamiento inteligente. Tu alma gemela está a solo un desliz de distancia.',
      freeToJoin: 'Gratis para unirse',
      verifiedProfiles: 'Perfiles verificados',
      secureDating: 'Citas seguras',
      whyChoose: 'Por qué elegir',
      heartsync: 'HeartSync',
      whyChooseSubtitle: 'Cada característica está diseñada para ayudarte a encontrar conexiones genuinas.',
      smartMatching: 'Emparejamiento Inteligente',
      smartMatchingDesc: 'Algoritmo con IA encuentra tu pareja ideal',
      safeSecure: 'Seguro y Protegido',
      safeSecureDesc: 'Perfiles verificados y mensajería encriptada',
      realConnections: 'Conexiones Reales',
      realConnectionsDesc: 'Millones de solteros genuinos en todo el mundo',
      premiumExperience: 'Experiencia Premium',
      premiumExperienceDesc: 'Experiencia de citas fluida y pulida',
      realStories: 'Historias Reales,',
      realLove: 'Amor Real',
      realStoriesSubtitle: 'Miles de parejas encontraron su final feliz en HeartSync.',
      readyToFindSoulmate: '¿Listo para encontrar tu alma gemela?',
      joinToday: 'Únete a HeartSync hoy y comienza tu viaje para encontrar el amor verdadero.',
      getStartedFree: 'Comenzar Gratis',
      howItWorks: 'Cómo Funciona',
      createProfile: 'Crear Perfil',
      createProfileDesc: 'Regístrate y crea tu perfil con fotos e intereses.',
      discoverMatches: 'Descubrir Coincidencias',
      discoverMatchesDesc: 'Desliza perfiles y da me gusta a personas con las que conectes.',
      startDating: 'Comenzar a Citarse',
      startDatingDesc: 'Encuentra coincidencias y comienza conversaciones significativas.',
      step: 'Paso',
      activeUsers: 'Usuarios Activos',
      matchesMade: 'Coincidencias',
      countries: 'Países',
      successRate: 'Tasa de Éxito',
    },
    common: {
      loading: 'Cargando...',
      profileUpdated: '¡Perfil actualizado correctamente!',
      failedToSave: 'Error al guardar los cambios. Por favor, inténtalo de nuevo.',
      anErrorOccurred: 'Ocurrió un error inesperado. Por favor, inténtalo de nuevo.',
    },
  },

  fr: {
    nav: {
      discover: 'Découvrir',
      messages: 'Messages',
      upgrade: 'Premium',
      settings: 'Paramètres',
      profile: 'Profil',
      signIn: 'Se connecter',
      getStarted: 'Commencer',
      logOut: 'Se déconnecter',
    },
    buttons: {
      save: 'Enregistrer',
      cancel: 'Annuler',
      edit: 'Modifier',
      delete: 'Supprimer',
      confirm: 'Confirmer',
      back: 'Retour',
      continue: 'Continuer',
      close: 'Fermer',
      send: 'Envoyer',
      search: 'Rechercher',
      startMatching: 'Commencer à chercher',
      viewMatches: 'Voir les matchs',
    },
    auth: {
      createAccount: 'Créer un compte',
      welcomeBack: 'Bon retour',
      startJourney: 'Commencez votre voyage pour trouver l\'amour',
      signInToContinue: 'Connectez-vous pour continuer',
      signUp: 'S\'inscrire',
      signIn: 'Se connecter',
      fullName: 'Nom complet',
      email: 'E-mail',
      password: 'Mot de passe',
      minCharacters: 'Min 6 caractères',
      byContinuing: 'En continuant, vous acceptez nos Conditions et Politique de confidentialité.',
    },
    settings: {
      title: 'Paramètres',
      websiteLanguage: 'Langue du site',
      languageDescription: 'Change la langue de l\'interface HeartSync uniquement.',
      signOut: 'Se déconnecter',
      signOutDescription: 'Se déconnecter de votre compte HeartSync',
      deleteAccount: 'Supprimer le compte',
      deleteAccountDescription: 'Supprimer définitivement votre compte et toutes les données',
      deleteConfirmTitle: 'Supprimer votre compte ?',
      deleteConfirmMessage: 'Cette action est permanente et ne peut pas être annulée. Toutes vos données, matchs et messages seront définitivement supprimés.',
      deleteConfirmNote: 'La suppression de compte nécessite une implémentation backend',
    },
    profile: {
      title: 'Mon Profil',
      bio: 'Biographie',
      bioPlaceholder: 'Parlez-nous de vous...',
      noBio: 'Pas encore de bio. Cliquez sur modifier pour en ajouter une !',
      photos: 'Photos',
      interests: 'Centres d\'intérêt',
      addInterest: 'Ajouter un intérêt...',
      add: 'Ajouter',
      main: 'PRINCIPALE',
      addPhoto: 'Ajouter une Photo',
      camera: 'Caméra',
      upload: 'Télécharger',
      likes: 'J\'aime',
      matches: 'Matchs',
      views: 'Vues',
      interestedIn: 'Intéressé par',
      gender: 'Genre',
      age: 'Âge',
      location: 'Localisation',
      name: 'Nom',
      premiumActive: 'Premium Actif',
      planDaysRemaining: 'plan · jours restants',
    },
    upgrade: {
      title: 'Passer à Premium',
      subtitle: 'Débloquez les messages illimités, voyez qui est en ligne et connectez-vous avec des profils exclusifs',
      yourePremium: 'Vous êtes Premium !',
      whatYouGet: 'Ce que vous obtenez',
      yourPremiumPerks: 'Vos avantages Premium',
      unlimitedMessages: 'Messages Illimités',
      unlimitedMessagesDesc: 'Discutez sans limites avec tous vos matchs',
      seeWhosOnline: 'Voir qui est en ligne',
      seeWhosOnlineDesc: 'Sachez quand vos matchs sont disponibles',
      unlimitedLikes: 'J\'aime illimités',
      unlimitedLikesDesc: 'Aimez autant de profils que vous voulez',
      superLikes: 'Super J\'aime',
      superLikesDesc: 'Démarquez-vous avec des super j\'aime illimités',
      prioritySupport: 'Support Prioritaire',
      prioritySupportDesc: 'Obtenez de l\'aide plus rapidement quand vous en avez besoin',
      vipBadge: 'Badge VIP',
      vipBadgeDesc: 'Affichez votre statut premium',
      choosePlan: 'Choisir',
      readyToFind: 'Prêt à trouver votre âme sœur ?',
      joinPremium: 'Rejoignez premium aujourd\'hui et débloquez toutes les fonctionnalités pour trouver votre connexion parfaite',
      upgradeNow: 'Mettre à niveau',
    },
    messages: {
      title: 'Messages',
      searchConversations: 'Rechercher des conversations...',
      noConversations: 'Pas encore de conversations. Commencez à swiper pour matcher !',
      tapToStart: 'Appuyez pour commencer à discuter...',
      sayHi: 'Dites bonjour à',
      sendAMessage: 'Envoyez un message pour commencer à discuter',
      typeMessage: 'Tapez un message...',
      subscribeToSend: 'Abonnez-vous pour envoyer des messages...',
      onlineNow: 'En ligne maintenant',
      lastSeen: 'Vu récemment',
      freeMessagesRemaining: 'message(s) gratuit(s) restant(s) avec',
      freeMessagesExhausted: 'Messages gratuits épuisés !',
      subscribeToContinue: 'Abonnez-vous pour continuer à discuter avec',
      subscribeNow: 'S\'abonner',
      slowDown: 'Ralentissez ! Max 10 messages par minute.',
      yourMessages: 'Vos Messages',
      selectConversation: 'Sélectionnez une conversation pour commencer à discuter',
    },
    discover: {
      title: 'Découvrir',
      profilesRemaining: 'profils restants',
      youveSeenEveryone: 'Vous avez vu tout le monde !',
      checkBackLater: 'Revenez plus tard pour de nouveaux profils.',
      startOver: 'Recommencer',
      swipeUpToPass: 'Balayez vers le haut pour passer • Gauche/Droite pour aimer',
      swipeOrTap: 'Balayez ou touchez les boutons pour interagir',
      keyboard: 'Clavier : ← Passer | → Aimer | ↑ Super J\'aime',
      verified: 'Vérifié',
      live: 'En direct',
    },
    matches: {
      title: 'Vos Matchs',
      subtitle: 'Les personnes qui vous ont aussi aimé',
      new: 'NOUVEAU',
    },
    landing: {
      aiPowered: '#1 Plateforme de Rencontres avec IA',
      findYourPerfectMatch: 'Trouvez votre',
      perfect: 'partenaire',
      match: 'parfait',
      landingSubtitle: 'Rejoignez des millions de célibataires qui trouvent des connexions significatives grâce à notre système de correspondance intelligent. Votre âme sœur n\'est qu\'à un swipe.',
      freeToJoin: 'Gratuit pour s\'inscrire',
      verifiedProfiles: 'Profils vérifiés',
      secureDating: 'Rencontres sécurisées',
      whyChoose: 'Pourquoi choisir',
      heartsync: 'HeartSync',
      whyChooseSubtitle: 'Chaque fonctionnalité est conçue pour vous aider à trouver des connexions authentiques.',
      smartMatching: 'Correspondance Intelligente',
      smartMatchingDesc: 'Algorithme IA trouve votre partenaire idéal',
      safeSecure: 'Sûr et Sécurisé',
      safeSecureDesc: 'Profils vérifiés et messagerie chiffrée',
      realConnections: 'Connexions Réelles',
      realConnectionsDesc: 'Des millions de célibataires authentiques dans le monde',
      premiumExperience: 'Expérience Premium',
      premiumExperienceDesc: 'Expérience de rencontres fluide et soignée',
      realStories: 'Histoires Réelles,',
      realLove: 'Vrai Amour',
      realStoriesSubtitle: 'Des milliers de couples ont trouvé leur bonheur sur HeartSync.',
      readyToFindSoulmate: 'Prêt à trouver votre âme sœur ?',
      joinToday: 'Rejoignez HeartSync aujourd\'hui et commencez votre voyage pour trouver le vrai amour.',
      getStartedFree: 'Commencer Gratuitement',
      howItWorks: 'Comment ça marche',
      createProfile: 'Créer un Profil',
      createProfileDesc: 'Inscrivez-vous et créez votre profil avec des photos et des centres d\'intérêt.',
      discoverMatches: 'Découvrir les Matchs',
      discoverMatchesDesc: 'Parcourez les profils et aimez les personnes avec qui vous connectez.',
      startDating: 'Commencer à Sortir',
      startDatingDesc: 'Matchez et commencez des conversations significatives.',
      step: 'Étape',
      activeUsers: 'Utilisateurs Actifs',
      matchesMade: 'Matchs',
      countries: 'Pays',
      successRate: 'Taux de Réussite',
    },
    common: {
      loading: 'Chargement...',
      profileUpdated: 'Profil mis à jour avec succès !',
      failedToSave: 'Échec de l\'enregistrement des modifications. Veuillez réessayer.',
      anErrorOccurred: 'Une erreur inattendue s\'est produite. Veuillez réessayer.',
    },
  },

  de: {
    nav: {
      discover: 'Entdecken',
      messages: 'Nachrichten',
      upgrade: 'Premium',
      settings: 'Einstellungen',
      profile: 'Profil',
      signIn: 'Anmelden',
      getStarted: 'Loslegen',
      logOut: 'Abmelden',
    },
    buttons: {
      save: 'Speichern',
      cancel: 'Abbrechen',
      edit: 'Bearbeiten',
      delete: 'Löschen',
      confirm: 'Bestätigen',
      back: 'Zurück',
      continue: 'Weiter',
      close: 'Schließen',
      send: 'Senden',
      search: 'Suchen',
      startMatching: 'Matching starten',
      viewMatches: 'Matches ansehen',
    },
    auth: {
      createAccount: 'Konto erstellen',
      welcomeBack: 'Willkommen zurück',
      startJourney: 'Beginnen Sie Ihre Reise, um Liebe zu finden',
      signInToContinue: 'Melden Sie sich an, um fortzufahren',
      signUp: 'Registrieren',
      signIn: 'Anmelden',
      fullName: 'Vollständiger Name',
      email: 'E-Mail',
      password: 'Passwort',
      minCharacters: 'Min. 6 Zeichen',
      byContinuing: 'Durch Fortfahren stimmen Sie unseren Nutzungsbedingungen und Datenschutzrichtlinien zu.',
    },
    settings: {
      title: 'Einstellungen',
      websiteLanguage: 'Website-Sprache',
      languageDescription: 'Ändert nur die Sprache der HeartSync-Oberfläche.',
      signOut: 'Abmelden',
      signOutDescription: 'Von Ihrem HeartSync-Konto abmelden',
      deleteAccount: 'Konto löschen',
      deleteAccountDescription: 'Ihr Konto und alle Daten dauerhaft löschen',
      deleteConfirmTitle: 'Ihr Konto löschen?',
      deleteConfirmMessage: 'Diese Aktion ist dauerhaft und kann nicht rückgängig gemacht werden. Alle Ihre Daten, Matches und Nachrichten werden dauerhaft gelöscht.',
      deleteConfirmNote: 'Kontolöschung erfordert Backend-Implementierung',
    },
    profile: {
      title: 'Mein Profil',
      bio: 'Biografie',
      bioPlaceholder: 'Erzählen Sie anderen von sich...',
      noBio: 'Noch keine Bio. Klicken Sie auf Bearbeiten, um eine hinzuzufügen!',
      photos: 'Fotos',
      interests: 'Interessen',
      addInterest: 'Interesse hinzufügen...',
      add: 'Hinzufügen',
      main: 'HAUPT',
      addPhoto: 'Foto hinzufügen',
      camera: 'Kamera',
      upload: 'Hochladen',
      likes: 'Gefällt mir',
      matches: 'Matches',
      views: 'Aufrufe',
      interestedIn: 'Interessiert an',
      gender: 'Geschlecht',
      age: 'Alter',
      location: 'Standort',
      name: 'Name',
      premiumActive: 'Premium Aktiv',
      planDaysRemaining: 'Plan · Tage verbleibend',
    },
    upgrade: {
      title: 'Auf Premium upgraden',
      subtitle: 'Schalten Sie unbegrenzte Nachrichten frei, sehen Sie, wer online ist, und verbinden Sie sich mit exklusiven Profilen',
      yourePremium: 'Sie sind Premium!',
      whatYouGet: 'Was Sie erhalten',
      yourPremiumPerks: 'Ihre Premium-Vorteile',
      unlimitedMessages: 'Unbegrenzte Nachrichten',
      unlimitedMessagesDesc: 'Chatten Sie ohne Limits mit all Ihren Matches',
      seeWhosOnline: 'Sehen Sie, wer online ist',
      seeWhosOnlineDesc: 'Wissen Sie, wann Ihre Matches verfügbar sind',
      unlimitedLikes: 'Unbegrenzte Likes',
      unlimitedLikesDesc: 'Liken Sie so viele Profile, wie Sie möchten',
      superLikes: 'Super Likes',
      superLikesDesc: 'Stechen Sie mit unbegrenzten Super Likes hervor',
      prioritySupport: 'Prioritäts-Support',
      prioritySupportDesc: 'Erhalten Sie schneller Hilfe, wenn Sie sie brauchen',
      vipBadge: 'VIP-Abzeichen',
      vipBadgeDesc: 'Zeigen Sie Ihren Premium-Status',
      choosePlan: 'Wählen',
      readyToFind: 'Bereit, Ihren Partner zu finden?',
      joinPremium: 'Werden Sie heute Premium-Mitglied und schalten Sie alle Funktionen frei, um Ihre perfekte Verbindung zu finden',
      upgradeNow: 'Jetzt upgraden',
    },
    messages: {
      title: 'Nachrichten',
      searchConversations: 'Konversationen suchen...',
      noConversations: 'Noch keine Konversationen. Beginnen Sie zu swipen, um zu matchen!',
      tapToStart: 'Tippen Sie, um zu chatten...',
      sayHi: 'Sagen Sie hallo zu',
      sendAMessage: 'Senden Sie eine Nachricht, um zu chatten',
      typeMessage: 'Nachricht eingeben...',
      subscribeToSend: 'Abonnieren Sie, um Nachrichten zu senden...',
      onlineNow: 'Jetzt online',
      lastSeen: 'Zuletzt gesehen',
      freeMessagesRemaining: 'kostenlose Nachricht(en) verbleibend mit',
      freeMessagesExhausted: 'Kostenlose Nachrichten aufgebraucht!',
      subscribeToContinue: 'Abonnieren Sie, um weiter mit zu chatten',
      subscribeNow: 'Jetzt abonnieren',
      slowDown: 'Langsamer! Max. 10 Nachrichten pro Minute.',
      yourMessages: 'Ihre Nachrichten',
      selectConversation: 'Wählen Sie eine Konversation, um zu chatten',
    },
    discover: {
      title: 'Entdecken',
      profilesRemaining: 'Profile verbleibend',
      youveSeenEveryone: 'Sie haben alle gesehen!',
      checkBackLater: 'Schauen Sie später nach neuen Profilen.',
      startOver: 'Neu beginnen',
      swipeUpToPass: 'Nach oben wischen zum Passen • Links/Rechts zum Liken',
      swipeOrTap: 'Wischen oder tippen Sie auf die Buttons zum Interagieren',
      keyboard: 'Tastatur: ← Passen | → Liken | ↑ Super Like',
      verified: 'Verifiziert',
      live: 'Live',
    },
    matches: {
      title: 'Ihre Matches',
      subtitle: 'Personen, die Sie auch gemocht haben',
      new: 'NEU',
    },
    landing: {
      aiPowered: '#1 KI-gestützte Dating-Plattform',
      findYourPerfectMatch: 'Finden Sie Ihr',
      perfect: 'perfektes',
      match: 'Match',
      landingSubtitle: 'Schließen Sie sich Millionen von Singles an, die durch unser intelligentes Matching-System bedeutungsvolle Verbindungen finden. Ihre Seelenverwandte ist nur ein Swipe entfernt.',
      freeToJoin: 'Kostenlos beitreten',
      verifiedProfiles: 'Verifizierte Profile',
      secureDating: 'Sicheres Dating',
      whyChoose: 'Warum',
      heartsync: 'HeartSync',
      whyChooseSubtitle: 'Jede Funktion ist darauf ausgelegt, Ihnen zu helfen, echte Verbindungen zu finden.',
      smartMatching: 'Intelligentes Matching',
      smartMatchingDesc: 'KI-Algorithmus findet Ihren idealen Partner',
      safeSecure: 'Sicher & Geschützt',
      safeSecureDesc: 'Verifizierte Profile und verschlüsselte Nachrichten',
      realConnections: 'Echte Verbindungen',
      realConnectionsDesc: 'Millionen authentischer Singles weltweit',
      premiumExperience: 'Premium-Erlebnis',
      premiumExperienceDesc: 'Nahtloses, poliertes Dating-Erlebnis',
      realStories: 'Echte Geschichten,',
      realLove: 'Echte Liebe',
      realStoriesSubtitle: 'Tausende von Paaren fanden ihr Glück auf HeartSync.',
      readyToFindSoulmate: 'Bereit, Ihre Seelenverwandte zu finden?',
      joinToday: 'Treten Sie HeartSync noch heute bei und beginnen Sie Ihre Reise, um wahre Liebe zu finden.',
      getStartedFree: 'Kostenlos starten',
      howItWorks: 'Wie es funktioniert',
      createProfile: 'Profil erstellen',
      createProfileDesc: 'Melden Sie sich an und erstellen Sie Ihr Profil mit Fotos und Interessen.',
      discoverMatches: 'Matches entdecken',
      discoverMatchesDesc: 'Swipen Sie durch Profile und liken Sie Personen, mit denen Sie sich verbinden.',
      startDating: 'Dating beginnen',
      startDatingDesc: 'Matchen Sie und beginnen Sie bedeutungsvolle Gespräche.',
      step: 'Schritt',
      activeUsers: 'Aktive Nutzer',
      matchesMade: 'Matches',
      countries: 'Länder',
      successRate: 'Erfolgsrate',
    },
    common: {
      loading: 'Wird geladen...',
      profileUpdated: 'Profil erfolgreich aktualisiert!',
      failedToSave: 'Fehler beim Speichern der Änderungen. Bitte versuchen Sie es erneut.',
      anErrorOccurred: 'Ein unerwarteter Fehler ist aufgetreten. Bitte versuchen Sie es erneut.',
    },
  },

  // ─── TURKISH (Türkçe) ──────────────────────────────────────────────────────
  tr: {
    nav: {
      discover: 'Keşfet',
      messages: 'Mesajlar',
      upgrade: 'Premium',
      settings: 'Ayarlar',
      profile: 'Profil',
      signIn: 'Giriş Yap',
      getStarted: 'Başla',
      logOut: 'Çıkış Yap',
    },
    buttons: {
      save: 'Kaydet',
      cancel: 'İptal',
      edit: 'Düzenle',
      delete: 'Sil',
      confirm: 'Onayla',
      back: 'Geri',
      continue: 'Devam Et',
      close: 'Kapat',
      send: 'Gönder',
      search: 'Ara',
      startMatching: 'Eşleşmeye Başla',
      viewMatches: 'Eşleşmeleri Görüntüle',
    },
    auth: {
      createAccount: 'Hesap Oluştur',
      welcomeBack: 'Tekrar Hoş Geldiniz',
      startJourney: 'Aşkı bulmak için yolculuğunuza başlayın',
      signInToContinue: 'Devam etmek için giriş yapın',
      signUp: 'Kayıt Ol',
      signIn: 'Giriş Yap',
      fullName: 'Ad Soyad',
      email: 'E-posta',
      password: 'Şifre',
      minCharacters: 'En az 6 karakter',
      byContinuing: 'Devam ederek Kullanım Koşulları ve Gizlilik Politikamızı kabul etmiş olursunuz.',
    },
    settings: {
      title: 'Ayarlar',
      websiteLanguage: 'Site Dili',
      languageDescription: 'Yalnızca HeartSync arayüzünün dilini değiştirir.',
      signOut: 'Çıkış yap',
      signOutDescription: 'HeartSync hesabınızdan çıkış yapın',
      deleteAccount: 'Hesabı sil',
      deleteAccountDescription: 'Hesabınızı ve tüm verilerinizi kalıcı olarak silin',
      deleteConfirmTitle: 'Hesabınızı silmek istiyor musunuz?',
      deleteConfirmMessage: 'Bu işlem kalıcıdır ve geri alınamaz. Tüm verileriniz, eşleşmeleriniz ve mesajlarınız kalıcı olarak silinecektir.',
      deleteConfirmNote: 'Hesap silme işlemi için arka uç gereklidir',
    },
    profile: {
      title: 'Profilim',
      bio: 'Hakkımda',
      bioPlaceholder: 'Kendinizi tanıtın...',
      noBio: 'Henüz biyografi yok. Eklemek için düzenle\'ye tıklayın!',
      photos: 'Fotoğraflar',
      interests: 'İlgi Alanları',
      addInterest: 'İlgi alanı ekle...',
      add: 'Ekle',
      main: 'ANA',
      addPhoto: 'Fotoğraf Ekle',
      camera: 'Kamera',
      upload: 'Yükle',
      likes: 'Beğeniler',
      matches: 'Eşleşmeler',
      views: 'Görüntülemeler',
      interestedIn: 'İlgilendiğim',
      gender: 'Cinsiyet',
      age: 'Yaş',
      location: 'Konum',
      name: 'Ad',
      premiumActive: 'Premium Aktif',
      planDaysRemaining: 'plan · gün kaldı',
    },
    upgrade: {
      title: 'Premium\'a Geç',
      subtitle: 'Sınırsız mesajlaşmanın kilidini açın, kimin çevrimiçi olduğunu görün ve özel profillerle bağlantı kurun',
      yourePremium: 'Premium Üyesiniz!',
      whatYouGet: 'Neler Kazanıyorsunuz',
      yourPremiumPerks: 'Premium Ayrıcalıklarınız',
      unlimitedMessages: 'Sınırsız Mesaj',
      unlimitedMessagesDesc: 'Tüm eşleşmelerinizle sınır tanımadan sohbet edin',
      seeWhosOnline: 'Çevrimiçi Olanları Görün',
      seeWhosOnlineDesc: 'Eşleşmeleriniz ne zaman müsait olduğunu bilin',
      unlimitedLikes: 'Sınırsız Beğeni',
      unlimitedLikesDesc: 'İstediğiniz kadar profil beğenin',
      superLikes: 'Süper Beğeniler',
      superLikesDesc: 'Sınırsız süper beğeni ile öne çıkın',
      prioritySupport: 'Öncelikli Destek',
      prioritySupportDesc: 'İhtiyaç duyduğunuzda daha hızlı yardım alın',
      vipBadge: 'VIP Rozeti',
      vipBadgeDesc: 'Premium statünüzü gösterin',
      choosePlan: 'Seç',
      readyToFind: 'Eşleşmenizi Bulmaya Hazır mısınız?',
      joinPremium: 'Bugün premium\'a katılın ve mükemmel bağlantınızı bulmak için tüm özelliklerin kilidini açın',
      upgradeNow: 'Şimdi Geç',
    },
    messages: {
      title: 'Mesajlar',
      searchConversations: 'Sohbet ara...',
      noConversations: 'Henüz sohbet yok. Eşleşmek için kaydırmaya başlayın!',
      tapToStart: 'Sohbet başlatmak için dokunun...',
      sayHi: 'Merhaba de:',
      sendAMessage: 'Sohbet başlatmak için mesaj gönderin',
      typeMessage: 'Mesaj yazın...',
      subscribeToSend: 'Mesaj göndermek için abone olun...',
      onlineNow: 'Şu an çevrimiçi',
      lastSeen: 'Son görülme yakın zamanda',
      freeMessagesRemaining: 'kişiyle kalan ücretsiz mesaj:',
      freeMessagesExhausted: 'Ücretsiz mesajlar tükendi!',
      subscribeToContinue: 'ile sohbet etmeye devam etmek için abone olun',
      subscribeNow: 'Şimdi Abone Ol',
      slowDown: 'Yavaşlayın! Dakikada en fazla 10 mesaj.',
      yourMessages: 'Mesajlarınız',
      selectConversation: 'Sohbet başlatmak için bir konuşma seçin',
    },
    discover: {
      title: 'Keşfet',
      profilesRemaining: 'profil kaldı',
      youveSeenEveryone: 'Herkesi gördünüz!',
      checkBackLater: 'Yeni profiller için daha sonra tekrar bakın.',
      startOver: 'Yeniden Başla',
      swipeUpToPass: 'Geçmek için yukarı • Beğenmek için sola/sağa kaydırın',
      swipeOrTap: 'Etkileşim için kaydırın veya düğmelere dokunun',
      keyboard: 'Klavye: ← Geç | → Beğen | ↑ Süper Beğen',
      verified: 'Doğrulanmış',
      live: 'Canlı',
    },
    matches: {
      title: 'Eşleşmeleriniz',
      subtitle: 'Sizi de beğenen kişiler',
      new: 'YENİ',
    },
    landing: {
      aiPowered: '#1 Yapay Zeka Destekli Tanışma Platformu',
      findYourPerfectMatch: 'Mükemmel',
      perfect: 'Eşinizi',
      match: 'Bulun',
      landingSubtitle: 'Akıllı eşleştirme sistemimiz aracılığıyla anlamlı bağlantılar kuran milyonlarca bekarla buluşun. Ruh eşiniz sadece bir kaydırma uzağınızda.',
      freeToJoin: 'Ücretsiz katılın',
      verifiedProfiles: 'Doğrulanmış profiller',
      secureDating: 'Güvenli tanışma',
      whyChoose: 'Neden',
      heartsync: 'HeartSync',
      whyChooseSubtitle: 'Her özellik, gerçek bağlantılar kurmanıza yardımcı olmak için tasarlanmıştır.',
      smartMatching: 'Akıllı Eşleştirme',
      smartMatchingDesc: 'Yapay zeka algoritması ideal eşinizi bulur',
      safeSecure: 'Güvenli ve Korumalı',
      safeSecureDesc: 'Doğrulanmış profiller ve şifreli mesajlaşma',
      realConnections: 'Gerçek Bağlantılar',
      realConnectionsDesc: 'Dünya genelinde milyonlarca gerçek bekar',
      premiumExperience: 'Premium Deneyim',
      premiumExperienceDesc: 'Kusursuz, şık bir tanışma deneyimi',
      realStories: 'Gerçek Hikayeler,',
      realLove: 'Gerçek Aşk',
      realStoriesSubtitle: 'Binlerce çift HeartSync\'te mutlu sonlarını buldu.',
      readyToFindSoulmate: 'Ruh Eşinizi Bulmaya Hazır mısınız?',
      joinToday: 'HeartSync\'e bugün katılın ve gerçek aşkı bulmak için yolculuğunuza başlayın.',
      getStartedFree: 'Ücretsiz Başla',
      howItWorks: 'Nasıl Çalışır',
      createProfile: 'Profil Oluştur',
      createProfileDesc: 'Kaydolun ve fotoğraflar ile ilgi alanlarınızla profilinizi oluşturun.',
      discoverMatches: 'Eşleşmeleri Keşfet',
      discoverMatchesDesc: 'Profilleri kaydırın ve bağlantı kurduğunuz kişileri beğenin.',
      startDating: 'Tanışmaya Başlayın',
      startDatingDesc: 'Eşleşin ve anlamlı sohbetler başlatın.',
      step: 'Adım',
      activeUsers: 'Aktif Kullanıcı',
      matchesMade: 'Eşleşme',
      countries: 'Ülke',
      successRate: 'Başarı Oranı',
    },
    common: {
      loading: 'Yükleniyor...',
      profileUpdated: 'Profil başarıyla güncellendi!',
      failedToSave: 'Değişiklikler kaydedilemedi. Lütfen tekrar deneyin.',
      anErrorOccurred: 'Beklenmedik bir hata oluştu. Lütfen tekrar deneyin.',
    },
  },
};
